name: Extended platform checks
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    with:
      platforms: '["ubuntu-latest", "macos-latest", "windows-latest"]'
